name: forca
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/getulioLT/forca_dart

environment:
  sdk: ^3.3.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
